import MainTemplate from "../components/MainTemplate";
import "./globals.css";
import { Inter } from "next/font/google";
import MainHead from "../components/MainHead";
import StyledComponentsRegistry from "../lib/registry";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <MainTemplate>
                        <MainHead></MainHead>
                        {children}
                    </MainTemplate>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
