import MainTemplate from '@/components/MainTemplate'
import './globals.css'
import { Inter } from 'next/font/google'
import MainHead from '@/components/MainHead'
import StyledComponentsRegistry from '@/lib/registry'
import { QueryClientProvider, useQueryClient } from '@tanstack/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const queryClient = useQueryClient()
  return (
    <html lang="en">
      <QueryClientProvider client={queryClient}>
      <body className={inter.className}>
      <StyledComponentsRegistry>
        <MainTemplate>
          <MainHead></MainHead>
          {children}
        </MainTemplate>
      </StyledComponentsRegistry>
        </body>
      </QueryClientProvider>
    </html>
  )
}
